---
title: "DATS 6101-11 Introduction to Data Science: First Project"
author: "Team 3 : Alejandro, Ebrima, Vidyullatha"
date: "`r Sys.Date()`"
output:
  html_document:
    code_folding: show
    number_sections: false
    toc: yes
    toc_depth: 3
    toc_float: yes
  pdf_document:
    toc: yes
    toc_depth: '3'
---

```{r init, include=F}
# Frequently used functions are loadPkg(), xkabledply(), xkablesummary(), uzscale(), etc.
library(devtools)
library(ezids)
```


```{r setup, include=FALSE}
# Some of common RMD options (and the defaults) are: 
# include=T, eval=T, echo=T, results='hide'/'asis'/'markup',..., collapse=F, warning=T, message=T, error=T, cache=T, fig.width=6, fig.height=4, fig.dim=c(6,4) #inches, fig.align='left'/'center','right', 
knitr::opts_chunk$set(results="markup", warning = F, message = F)
# Can globally set option for number display format.
options(scientific=T, digits = 3) 
# options(scipen=9, digits = 3) 
```

# 1. Summary of the dataset 

#### Load the dataset into R
```{r}
library(readr)
df <- read_csv("./data/StudentsPerformance.csv")
```

#### Display the first 5 records
```{r}
head(df, 5)
```
#### Structure of dataset (variable types)
```{r}
str(df)
```
#### Basic summary statistics
```{r}
summary(df)
```
#### Column names and unique values
```{r}
names(df)
sapply(df, function(x) length(unique(x)))
```



